Return-Path: <zhtirlik82@gmail.com>
Received: from mail-wm1-f46.google.com (mail-wm1-f46.google.com [209.85.128.46])
	by mail.tirlik.kz (Postfix) with ESMTPS id D07F1140726B
	for <7admin@tirlik.kz>; Sun, 22 Dec 2024 13:33:43 +0000 (UTC)
DKIM-Filter: OpenDKIM Filter v2.11.0 mail.tirlik.kz D07F1140726B
Authentication-Results: mail.tirlik.kz;
	dkim=pass (2048-bit key) header.d=gmail.com header.i=@gmail.com header.b="aPYV0YSq"
Received: by mail-wm1-f46.google.com with SMTP id 5b1f17b1804b1-4362f61757fso33511695e9.2
        for <7admin@tirlik.kz>; Sun, 22 Dec 2024 05:33:43 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20230601; t=1734874422; x=1735479222; darn=tirlik.kz;
        h=to:subject:message-id:date:from:in-reply-to:references:mime-version
         :from:to:cc:subject:date:message-id:reply-to;
        bh=SSV3qXruHpgWC855Y8r/eQGVIns8Ee7TBt+YgMWTAVc=;
        b=aPYV0YSqXDGp34Nsk7t+vLEIugsxQeeoOCMdxJuLAjg0boUC7FehVPzbZ0OPvSR6wj
         659/oV6b72KghyGdSOlhoDE06Wcy6ngfHmmz2pMSicv77ArYGWZxCDOrXz5jezibFb9h
         Rk4Mnm3cDyEVXd+IsVAF4mFo51GxIZ1kGZwb6nUIuXSOJ8eN/zw+pZnO04DwRdvVGN0A
         Pdx4LyO9N2HGS5i7lowWIZdVpkMRn2EbmZo4uswZElxhR0mAFCa+EngyAJXnQ2eomktl
         UwvRBEqh1ytgF7MDR/+CdYh5A3bY4pdMEGHT89JTfKtvqF3FzMjwp4mnCoJdr6CgyHbA
         d5Iw==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20230601; t=1734874422; x=1735479222;
        h=to:subject:message-id:date:from:in-reply-to:references:mime-version
         :x-gm-message-state:from:to:cc:subject:date:message-id:reply-to;
        bh=SSV3qXruHpgWC855Y8r/eQGVIns8Ee7TBt+YgMWTAVc=;
        b=T1ww9q3CEl0qeXrYQcWuzs6RN2UgjSdMNA7C8DEFA3lNXoXynOvxVW4IAwOr9uK2po
         hIOs+R+fch2Ee9Zsqvw8vc01sx9mWVtwt9JIA2o7/ejlLv3gUR7W2nzulNX0++RkT5+d
         ta2t/IhXdJm5Y0kxCSZCKmkpbodJyUtbLJOTOb7Q1TJbILTqTqJbl15MVj4zral691MZ
         utnOudCfO5Buzpp10qDb4iKPE+b06HtSX2jJUKFcOU+Hm3GZ8iBpfTiHwNTqYe8py4ey
         MWAqvaP6/GKAzFksWckHbgujFv1V5Jwa5FrRhR5ee/lRw5Xs2N8zTSfXSUL3tP+/Owow
         hJqw==
X-Gm-Message-State: AOJu0YxTXeuYQsNXE6v8tOCjivU7pFEGSAoFBr0aIpv9mhzwRx3k4Z0l
	mC+6IVlhKwCfESxdrHM9Uyw/Gv0SBAtnD0Icmm54m2UtngGQhqIux//Ds59bgL7cyUhqdrHQ5Xn
	C4ur8RBFKcOxTwl4STj4dR0bNHGdAgg==
X-Gm-Gg: ASbGncswDXr7MC0E3jjeOrWcpZABXvkZt0WMzPBbdsluuS8Jl6d8zmH8DJ9WdkAFIDX
	IojfnHxjp4LHn1JqQFF6+og4V5U85lLy3dnnu5Q==
X-Google-Smtp-Source: AGHT+IFLxVnBE7KVgq7yqc2QMSmiAz5YColePWLLsT66NetMKvSc2csYhEf6LfINFxX78uTRXrscsGbRvegKhglCMaE=
X-Received: by 2002:a05:600c:1c9f:b0:435:32e:8270 with SMTP id
 5b1f17b1804b1-43668642f9dmr80682375e9.14.1734874422103; Sun, 22 Dec 2024
 05:33:42 -0800 (PST)
MIME-Version: 1.0
References: <3a4caa57c6c796961d2694b817c05623.squirrel@tirlik.kz>
In-Reply-To: <3a4caa57c6c796961d2694b817c05623.squirrel@tirlik.kz>
From: =?UTF-8?B?0JbQsNC90LjQsdC10Log0JrQsNC60LjQvNCx0LDQtdCy?= <zhtirlik82@gmail.com>
Date: Sun, 22 Dec 2024 18:33:29 +0500
Message-ID: <CA+b=+qW+X3nfoDmnyKD08KCPnUUFv+Fhr79KJ77kSuj15X0AYg@mail.gmail.com>
Subject: Re:
To: 7admin@tirlik.kz
Content-Type: multipart/alternative; boundary="000000000000a8da3f0629dbed92"

--000000000000a8da3f0629dbed92
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: base64

0rDSr9KT0qMNCg0K0YHQsSwgMjEg0LTQtdC6LiAyMDI04oCv0LMuLCAyMjoxMiA8N2FkbWluQHRp
cmxpay5rej46DQoNCj4gZGRkZA0KPg0K
--000000000000a8da3f0629dbed92
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

<p dir=3D"ltr">=D2=B0=D2=AF=D2=93=D2=A3</p>
<br><div class=3D"gmail_quote gmail_quote_container"><div dir=3D"ltr" class=
=3D"gmail_attr">=D1=81=D0=B1, 21 =D0=B4=D0=B5=D0=BA. 2024=E2=80=AF=D0=B3., =
22:12  &lt;<a href=3D"mailto:7admin@tirlik.kz">7admin@tirlik.kz</a>&gt;:<br=
></div><blockquote class=3D"gmail_quote" style=3D"margin:0 0 0 .8ex;border-=
left:1px #ccc solid;padding-left:1ex">dddd<br>
</blockquote></div>

--000000000000a8da3f0629dbed92--
